# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Avalonia";
    version = "11.0.0";
    hash = "sha256-7QE0MtD1QDiG3gRx5xW33E33BXyEtASQSw+Wi3Lmy3E=";
  })
  (fetchNuGet {
    pname = "Avalonia";
    version = "11.1.0-rc1";
    hash = "sha256-NjSOKJKWcrKcqEP/FAs14Y+ZzeitSyd7FvQaWpTUqhA=";
  })
  (fetchNuGet {
    pname = "Avalonia.Angle.Windows.Natives";
    version = "2.1.22045.20230930";
    hash = "sha256-RxPcWUT3b/+R3Tu5E5ftpr5ppCLZrhm+OTsi0SwW3pc=";
  })
  (fetchNuGet {
    pname = "Avalonia.AvaloniaEdit";
    version = "11.0.6";
    hash = "sha256-2GymzDUKkabTGXrO1zel70QI2chfDsHrz1S5onQhqu4=";
  })
  (fetchNuGet {
    pname = "Avalonia.BuildServices";
    version = "0.0.28";
    hash = "sha256-7NQWQl3xrBDOXhGihCkt5DIrws48KyDGon/7+gPzMDU=";
  })
  (fetchNuGet {
    pname = "Avalonia.BuildServices";
    version = "0.0.29";
    hash = "sha256-WPHRMNowRnYSCh88DWNBCltWsLPyOfzXGzBqLYE7tRY=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.ColorPicker";
    version = "11.1.0-rc1";
    hash = "sha256-u8CAZJIRbuXGxRivaGPlaXfxPQf7OCKUAU6jisYdaZs=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.DataGrid";
    version = "11.1.0-rc1";
    hash = "sha256-0iiNKBQCmnO5rZUzGcsju5O81e0URM35FEz1FTZUHls=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.TreeDataGrid";
    version = "11.0.10";
    hash = "sha256-1R2AFOKQQPemN7qXsdxCGXcfMSRztRiC86DLqiV6CpY=";
  })
  (fetchNuGet {
    pname = "Avalonia.Desktop";
    version = "11.1.0-rc1";
    hash = "sha256-8j1qWibl5JUqAaS893TEzBQoWzsVqgAVMX4xVxWmKWo=";
  })
  (fetchNuGet {
    pname = "Avalonia.Diagnostics";
    version = "11.1.0-rc1";
    hash = "sha256-UD0djXIpzVKxeWw5B99AGsibUy5hGF70mI9vZny6vOk=";
  })
  (fetchNuGet {
    pname = "Avalonia.FreeDesktop";
    version = "11.1.0-rc1";
    hash = "sha256-Oh9QqPL/O3a0kUsv/IHAg3/lDzQLRl5v4L5mGoqasbQ=";
  })
  (fetchNuGet {
    pname = "Avalonia.Native";
    version = "11.1.0-rc1";
    hash = "sha256-BHdL5g1rYx7hOYXE60dmzlZ1N+7NFl8SD/SeM9nqEKA=";
  })
  (fetchNuGet {
    pname = "Avalonia.ReactiveUI";
    version = "11.1.0-rc1";
    hash = "sha256-RaSbdi+TtAeNR3NggoM4TsmMMhwGE/uJyrxBF6ubM94=";
  })
  (fetchNuGet {
    pname = "Avalonia.Remote.Protocol";
    version = "11.0.0";
    hash = "sha256-gkVpdbk/0RDM7Hhq0jwZwltDpTsGRmbX+ZFTjWYYoKw=";
  })
  (fetchNuGet {
    pname = "Avalonia.Remote.Protocol";
    version = "11.1.0-rc1";
    hash = "sha256-fawaToCwZWwvRJQKYVJYZeMWQEW8XPrNBJEZ3lXLOe8=";
  })
  (fetchNuGet {
    pname = "Avalonia.Skia";
    version = "11.0.0";
    hash = "sha256-A01nrs3Ij1eTo6tPmu7++T1K+Wo/H/9LvpeuOUGbQeU=";
  })
  (fetchNuGet {
    pname = "Avalonia.Skia";
    version = "11.1.0-rc1";
    hash = "sha256-F06oKB97Se3JxGZRAsQCGklu5wS64agGCSUT9IBQcVU=";
  })
  (fetchNuGet {
    pname = "Avalonia.Svg.Skia";
    version = "11.1.0-rc1";
    hash = "sha256-prRC6GZ+dtVdYFjlGU20xHrkNHB69jegEjKFv+GK7Vw=";
  })
  (fetchNuGet {
    pname = "Avalonia.Themes.Fluent";
    version = "11.1.0-rc1";
    hash = "sha256-Yy3gHV9SoZAVFHuAABjBqfdRNEVfFprAdx38e7tNucU=";
  })
  (fetchNuGet {
    pname = "Avalonia.Themes.Simple";
    version = "11.1.0-rc1";
    hash = "sha256-QfNeSeCbwQlVRCFYa8BjJlYnkSk3TC7ACenG3RAUFWU=";
  })
  (fetchNuGet {
    pname = "Avalonia.Win32";
    version = "11.1.0-rc1";
    hash = "sha256-kScofxDFq4+fAogQcSTu7axKBF2cqUjwH4c9ZbKx7s4=";
  })
  (fetchNuGet {
    pname = "Avalonia.X11";
    version = "11.1.0-rc1";
    hash = "sha256-m0MTISz3KlQrccEIkSR+XEoiXY/iUGnQuH8NFPV6Y/Y=";
  })
  (fetchNuGet {
    pname = "AvaloniaEdit.TextMate";
    version = "11.0.6";
    hash = "sha256-7QpWP6gt0aA/2P+WK0JzX9n90R0Gy/e3cQntAUmAuBw=";
  })
  (fetchNuGet {
    pname = "BitFaster.Caching";
    version = "2.5.0";
    hash = "sha256-HUGbbOYdGnWS2XYpgmDsWaAWCZzQFkdPCqfl9OBd5eA=";
  })
  (fetchNuGet {
    pname = "CliWrap";
    version = "3.6.6";
    hash = "sha256-2fdVlcdgA5Phl/DKas/CKF828GwiJ9L8lB1c1zXU9Qo=";
  })
  (fetchNuGet {
    pname = "ColorDocument.Avalonia";
    version = "11.0.3-a1";
    hash = "sha256-Pkh5FX+4pBzep5oCCyhIiR559QyFCEb1vrfEgG0wREw=";
  })
  (fetchNuGet {
    pname = "ColorTextBlock.Avalonia";
    version = "11.0.3-a1";
    hash = "sha256-fWJuApxnJLISayQJIKEBVOt/t1Qyj+0s+RezZkMnPio=";
  })
  (fetchNuGet {
    pname = "DynamicData";
    version = "8.3.27";
    hash = "sha256-iPZfL1x36PLf5Lq96zRFvR5OLcoRn7OdJIao98X8wac=";
  })
  (fetchNuGet {
    pname = "DynamicData";
    version = "8.4.1";
    hash = "sha256-r+haH5VlmZFJTEJ3UedsYybw+oddn/CSvfm6x7PrrQ4=";
  })
  (fetchNuGet {
    pname = "ExCSS";
    version = "4.2.3";
    hash = "sha256-M/H6P5p7qqdFz/fgAI2MMBWQ7neN/GIieYSSxxjsM9I=";
  })
  (fetchNuGet {
    pname = "FlatSharp.Compiler";
    version = "7.6.0";
    hash = "sha256-bYRnKdem5I/0YAHupyIzpHfndPFNH22QU3MAxlKQ5uQ=";
  })
  (fetchNuGet {
    pname = "FlatSharp.Runtime";
    version = "7.6.0";
    hash = "sha256-rLiWZ8hmDSq5qawXc00zcMxrH/Zi/IlZOrXRx4e6SdQ=";
  })
  (fetchNuGet {
    pname = "FluentResults";
    version = "3.15.2";
    hash = "sha256-NhS7sLhgXDAI4Qwb285HWRtPfUDN6K0tTkKx2QRsI9w=";
  })
  (fetchNuGet {
    pname = "Fody";
    version = "6.8.0";
    hash = "sha256-2laYscz0i0LalGTAup7dsh6XlYRZSojYpp8XOwZJJfg=";
  })
  (fetchNuGet {
    pname = "FomodInstaller.Interface";
    version = "1.2.0";
    hash = "sha256-sxylVEA7uiaBtxbQHAeRElsVbZPIj2nm27Ozlik8wmg=";
  })
  (fetchNuGet {
    pname = "FomodInstaller.Scripting";
    version = "1.0.0";
    hash = "sha256-GNqbLS+lU6aNThUUCfJpmZgP+rd4lF0fKyfMn2Y7Ckg=";
  })
  (fetchNuGet {
    pname = "FomodInstaller.Scripting.XmlScript";
    version = "1.0.0";
    hash = "sha256-fbekooynf0jQD0k0zbYueDvOTxPa3FIZUKjCcVMPeeY=";
  })
  (fetchNuGet {
    pname = "FomodInstaller.Utils";
    version = "1.0.0";
    hash = "sha256-H0Fc79msO6GhYstzqtZk9ttRcqxtXuDT9v0zQBwDRHI=";
  })
  (fetchNuGet {
    pname = "GameFinder";
    version = "4.2.4";
    hash = "sha256-weK14/DduSymh7G5SaxQH3PsJsvAe9sDdRrrQOsX0aM=";
  })
  (fetchNuGet {
    pname = "GameFinder.Common";
    version = "4.2.4";
    hash = "sha256-YPVBPHoBDreQlITXIff/jbQpDczZPQ4mKNrcz3xKzyQ=";
  })
  (fetchNuGet {
    pname = "GameFinder.RegistryUtils";
    version = "4.2.4";
    hash = "sha256-xqr6HK6smT2JHUL2+vV8qj1pfywjJbhIwEGxK0PJV0s=";
  })
  (fetchNuGet {
    pname = "GameFinder.StoreHandlers.EADesktop";
    version = "4.2.4";
    hash = "sha256-kRuw1sYg+9Zv92prYhFKdihD/IazeAFb9GO3oeHxF+I=";
  })
  (fetchNuGet {
    pname = "GameFinder.StoreHandlers.EGS";
    version = "4.2.4";
    hash = "sha256-cJNt7RJ/Zeo+9ECPWKxaseomm9alkrkYMl8uHuy6B6I=";
  })
  (fetchNuGet {
    pname = "GameFinder.StoreHandlers.GOG";
    version = "4.2.4";
    hash = "sha256-YwqM2j0FVB+afVkkcw1jOTiRkqehaJM3fvw66f3zz8U=";
  })
  (fetchNuGet {
    pname = "GameFinder.StoreHandlers.Origin";
    version = "4.2.4";
    hash = "sha256-npSZ4VieuOSe5BnunF6aDoKuH+4gX2RZtnKhUZVF1Cc=";
  })
  (fetchNuGet {
    pname = "GameFinder.StoreHandlers.Steam";
    version = "4.2.4";
    hash = "sha256-GFQe3JszsCaq7WBX6+DDXyQEubnV6uoGmBGVMgGj+bA=";
  })
  (fetchNuGet {
    pname = "GameFinder.StoreHandlers.Xbox";
    version = "4.2.4";
    hash = "sha256-TuUqhl4RDz40x6iYqiaAZT0yfP+N801h+7k22bXWIMs=";
  })
  (fetchNuGet {
    pname = "GameFinder.Wine";
    version = "4.2.4";
    hash = "sha256-wdZ4ulm7jbEpWXWtmErQ73Mj7Pbe9GFugjWdQID8YYg=";
  })
  (fetchNuGet {
    pname = "Google.Protobuf";
    version = "3.22.5";
    hash = "sha256-KuPCqobX6vE9RYElAN9vw+FPonFipms7kE/cRDCLmSQ=";
  })
  (fetchNuGet {
    pname = "Grpc.Core.Api";
    version = "2.52.0";
    hash = "sha256-ISgN3zWwvV8qD7JFkaYveLbke09+UtUBy3Tux+ZHLNc=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Client";
    version = "2.52.0";
    hash = "sha256-4Rhb8PIoV2BiohfRwzx1GYDPbcfqxGAmL2uB0atFFTk=";
  })
  (fetchNuGet {
    pname = "Grpc.Net.Common";
    version = "2.52.0";
    hash = "sha256-XoY+jt+JIt6SzvCjUSXKKa9Q8Bu5UrNJv2z1hCBKDrY=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp";
    version = "2.8.2.3";
    hash = "sha256-4tbdgUabPjlkBm3aUFeocj4Fdslmms2olDFpzOLyqoQ=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp";
    version = "7.3.0";
    hash = "sha256-LlPQO/NYgIMWicvLOtWsQzCp512QpIImYDP9/n2rDOc=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp";
    version = "7.3.0.2";
    hash = "sha256-ibgoqzT1NV7Qo5e7X2W6Vt7989TKrkd2M2pu+lhSDg8=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Linux";
    version = "2.8.2.3";
    hash = "sha256-3xwVfNfKTkuLdnT+e3bfG9tNTdEmar7ByzY+NTlUKLg=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Linux";
    version = "7.3.0.2";
    hash = "sha256-SSfyuyBaduGobJW+reqyioWHhFWsQ+FXa2Gn7TiWxrU=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.macOS";
    version = "2.8.2.3";
    hash = "sha256-ZohUEaovj/sRB4rjuJIOq6S9eim3m+qMlpHIebNDTRQ=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.macOS";
    version = "7.3.0";
    hash = "sha256-6oFcdKb17UX5wyAUeCCKXGvzkf0w3MNdZOVMvs54tqw=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.macOS";
    version = "7.3.0.2";
    hash = "sha256-dmEqR9MmpCwK8AuscfC7xUlnKIY7+Nvi06V0u5Jff08=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.WebAssembly";
    version = "2.8.2.3";
    hash = "sha256-ZsiBGpXfODHUHPgU/50k9QR/j6Klo7rsB0SUt8zYcBA=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.WebAssembly";
    version = "7.3.0.2";
    hash = "sha256-aEZr9uKAlCTeeHoYNR1Rs6L3P54765CemyrgJF8x09c=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Win32";
    version = "2.8.2.3";
    hash = "sha256-5GSzM5IUoOwK+zJg0d74WlT3n1VZly8pKlyjiqVocCI=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Win32";
    version = "7.3.0";
    hash = "sha256-WnB7l73hneU9Kpbm8S9zEYbZHjFre24vWz0vl8+v28M=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Win32";
    version = "7.3.0.2";
    hash = "sha256-x4iM3NHs9VyweG57xA74yd4uLuXly147ooe0mvNQ8zo=";
  })
  (fetchNuGet {
    pname = "HtmlAgilityPack";
    version = "1.11.52";
    hash = "sha256-52YYrpZKJO1MrgST7K2u8SY00YyKvg43J4AMIw83BAQ=";
  })
  (fetchNuGet {
    pname = "Humanizer";
    version = "2.14.1";
    hash = "sha256-1wGwf5KAmDeiH0Dz8KcTdZw+UMkiNsjKOIOt/VJnnqE=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core";
    version = "2.14.1";
    hash = "sha256-EXvojddPu+9JKgOG9NSQgUTfWq1RpOYw7adxDPKDJ6o=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.af";
    version = "2.14.1";
    hash = "sha256-8CCgI7OweSa53cZWZBXQ8a7VVt/NPP16zHVBZvzU9KQ=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ar";
    version = "2.14.1";
    hash = "sha256-JRoP+brQgYBZI8OccH/jaM1Z482ZWBiqU2XL3KsIPw8=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.az";
    version = "2.14.1";
    hash = "sha256-ubwkbes9zrrisuXTcT4ZgOAiFsUieC6OLd4pgzxsE40=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.bg";
    version = "2.14.1";
    hash = "sha256-Xv6DP1xxxGVUfP44TZasWpxgQ/DkriljvmIMtHf+nGk=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.bn-BD";
    version = "2.14.1";
    hash = "sha256-6JpReIc3fkExvJIXzk6fUw56wJ78aTEg1dWQ6o+dQow=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.cs";
    version = "2.14.1";
    hash = "sha256-MGL86KxSbz0PkDo9+NRj6h1fDjPZXlxAtYNf0Zreg/4=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.da";
    version = "2.14.1";
    hash = "sha256-Gpw8kJbgz0KQS2mGY5tmrHqpgUO4abD7dSKIy//ONYM=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.de";
    version = "2.14.1";
    hash = "sha256-Eswv8aEQoxI9MZr2CvWtBUn5X9JRZTWQjRzHJkGj80g=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.el";
    version = "2.14.1";
    hash = "sha256-wCK2Uy/AV6FxPUSUM0NMbV14pAP+ss25AaVAHMQIeJA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.es";
    version = "2.14.1";
    hash = "sha256-iEHiQXKwg0ABDxh//HSrzwaVOlilQBFI96+GYzzTMwQ=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.fa";
    version = "2.14.1";
    hash = "sha256-2Js7k3nvwJvxAjq3yoLn7PUY2S8+vXfgESwU4SbvjaA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.fi-FI";
    version = "2.14.1";
    hash = "sha256-jOWo43r3dhiBsV9cCoDfqK/YqWj5LejZsnfkG6mlkpA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.fr";
    version = "2.14.1";
    hash = "sha256-WCbA+f4B3g/ml7KrkHkzpU2Fj38HtWc/ujoVY5F3lk4=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.fr-BE";
    version = "2.14.1";
    hash = "sha256-GydVmoEy+lwEQ1nM39QXSRhYNchqM47p7qhUEimN4Cw=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.he";
    version = "2.14.1";
    hash = "sha256-MMf3qjJ+yzxjMxOR7wMWf+eErxWLqpsdWKFhjNCOsyM=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.hr";
    version = "2.14.1";
    hash = "sha256-kBv2I9ns6L6D4XfXfyZS1VM6+YwF4yUkCmCA5zqvsok=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.hu";
    version = "2.14.1";
    hash = "sha256-vRje+kxqOsl1JCXAE0yDKvauUumzuEhNcnhNsdIdgVM=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.hy";
    version = "2.14.1";
    hash = "sha256-UL7PsK4msT5c96lk70/bVAxN63B71l8VOFtvuJQH9a0=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.id";
    version = "2.14.1";
    hash = "sha256-nIl64gCuZh4D527qI2hfQRvzt1mTJUCDGMIZwpS3C/A=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.is";
    version = "2.14.1";
    hash = "sha256-38vUQ1aVtlhK15kP9ZlDO0Nl0DcOA5iHx6F2SPN1gYM=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.it";
    version = "2.14.1";
    hash = "sha256-4ne0VRNi9OAj3bGCQgCy1BNYKMizoHykJ/lchmCsWdc=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ja";
    version = "2.14.1";
    hash = "sha256-oAilMM8J6LumV6qv3gSIBNTm7u2L4vV38cQXtME3PhM=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ko-KR";
    version = "2.14.1";
    hash = "sha256-b70HQl2IWVPATtaYGDyJ+Z6ioPtrM53vXzfTCHYgxpQ=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ku";
    version = "2.14.1";
    hash = "sha256-8LiEH7MaapMtkHFMj7Y3pG+g0QYuIa5gD3VR9nYQn+k=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.lv";
    version = "2.14.1";
    hash = "sha256-zyCsE5cD++u5shNIqCQUd+66FkUWOl+NfFrs2JduCaQ=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ms-MY";
    version = "2.14.1";
    hash = "sha256-pSdZLUi9oWo78nBh2DJunPhDR7THdZSZP0msCVbPsrY=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.mt";
    version = "2.14.1";
    hash = "sha256-mkX2reEvNpx9w6gtZw+6bkrnj3Di1qgVDMr9q0IeKCw=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.nb";
    version = "2.14.1";
    hash = "sha256-QvYJHqjO/SrelWYgtm8Sc7axs7J8wbJE+GbTgVw5LYs=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.nb-NO";
    version = "2.14.1";
    hash = "sha256-YW8y2XkmHjwqf2fztNB3rsn3+CgslF1TclITwp0fA9g=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.nl";
    version = "2.14.1";
    hash = "sha256-bQM7aXNQMBY+65NfMVQz/xYz9Ad2JC+ryXoB4lcYgmA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.pl";
    version = "2.14.1";
    hash = "sha256-IrPxHI4uQvBeMM9/8PaNueKwVkbN+1zFQlNWRjNfXEA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.pt";
    version = "2.14.1";
    hash = "sha256-XrlC15HNJFmDwLpHIUHb3Bec9A79msQCRB9Dvz8w4l0=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ro";
    version = "2.14.1";
    hash = "sha256-llXtfq4Tr5V2Q4dVD7J0IKITtpiWrFs50DAtJhcSuRI=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.ru";
    version = "2.14.1";
    hash = "sha256-lD0dB3mkbFfGExwVWZk6fv24MyQQ8Cdv5OrleuZeChg=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.sk";
    version = "2.14.1";
    hash = "sha256-EmyE+wssZwY6tAuEiFXGn5/yzVMZe7QEuTjOcByOXaA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.sl";
    version = "2.14.1";
    hash = "sha256-sWWxh7KZ8Y3Ps6GbBOHbU2GMsNZfkM+BOnUChf3fz4s=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.sr";
    version = "2.14.1";
    hash = "sha256-/bA3LULRFn5WYmCscr5R5vaFRjeHC0xjNiF7PXEJ8r0=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.sr-Latn";
    version = "2.14.1";
    hash = "sha256-43+o6oj0UNRJKiFoh57MGPSzlsWAq0eRtzlCrewDmVM=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.sv";
    version = "2.14.1";
    hash = "sha256-9lXrHveKDs1y/W3Qxd+MVcohhKEU7zNPx21GBVPp/rA=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.th-TH";
    version = "2.14.1";
    hash = "sha256-ldCsXINSvL2xom0SCtVQy+qX1IN5//EUoyIOwXiJ3k8=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.tr";
    version = "2.14.1";
    hash = "sha256-VZnO1vMXiR7egKEKJ6lBsj7eNgxhFzakFWsYYRW4u2U=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.uk";
    version = "2.14.1";
    hash = "sha256-rdvleUrKbj3c06A0O2MkgAZLtXLro9SPB1YqAGE1Vyg=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.uz-Cyrl-UZ";
    version = "2.14.1";
    hash = "sha256-Qso1Iz9MTLs63x4F00kK31TZAN4AoFaFsuVzM+1z38k=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.uz-Latn-UZ";
    version = "2.14.1";
    hash = "sha256-sVnkZTuEaHfMJIAZmSCqsspnKkYxK9eVBQZnAAqHNW4=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.vi";
    version = "2.14.1";
    hash = "sha256-5wDt72+HdNN3mt/iJkxV9LaH13Jc1qr1vB4Lz8ahIPs=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.zh-CN";
    version = "2.14.1";
    hash = "sha256-Z3qfFWyovcVT4Hqy51lgW2xGwyfI//Yfv90E0Liy1sw=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.zh-Hans";
    version = "2.14.1";
    hash = "sha256-BTGkMEkQYJKRp858EU7hwNOdsHRT+w6vAMa6H8JIyX4=";
  })
  (fetchNuGet {
    pname = "Humanizer.Core.zh-Hant";
    version = "2.14.1";
    hash = "sha256-N3D1z5aoGwAZ6+ZxrWMtXgacvQcgDG+aLrQQI9uysmM=";
  })
  (fetchNuGet {
    pname = "ini-parser-netstandard";
    version = "2.5.2";
    hash = "sha256-idb2hvuDlxl83x0yttGHnTgEQmwLLdUT7QfMeGDXVJE=";
  })
  (fetchNuGet {
    pname = "JetBrains.Annotations";
    version = "2023.3.0";
    hash = "sha256-/Eykez68qYMO5mlmUelzAke8aJehyp8fspO5Z+yt5G4=";
  })
  (fetchNuGet {
    pname = "K4os.Compression.LZ4";
    version = "1.3.7-beta";
    hash = "sha256-mMNIMLSXnKFF3oAgX+k/n0wipxyRDGE1z2BrI2+7ALc=";
  })
  (fetchNuGet {
    pname = "LinqGen";
    version = "0.3.1";
    hash = "sha256-Yyt1uShHigHVCIjPT8jL2Kth9L9yq1MGrCM5w2+tj9o=";
  })
  (fetchNuGet {
    pname = "LiveChartsCore";
    version = "2.0.0-rc2";
    hash = "sha256-JSw2bwHOvUDx+axSufcvKSD9RPmqi366tbiIcsym3As=";
  })
  (fetchNuGet {
    pname = "LiveChartsCore.SkiaSharpView";
    version = "2.0.0-rc2";
    hash = "sha256-tKBTT75B77po0jDqWJL0mOzXkCKmHAGPlQV3biKtZdw=";
  })
  (fetchNuGet {
    pname = "LiveChartsCore.SkiaSharpView.Avalonia";
    version = "2.0.0-rc2";
    hash = "sha256-pHMtCkoz4sz2MLlVGFbFwwONLC3vzy+9Cg0OmEJ+f/s=";
  })
  (fetchNuGet {
    pname = "Markdown.Avalonia.Tight";
    version = "11.0.3-a1";
    hash = "sha256-KkRzr8BXmUCGCVv/64gg1aiXHUY0yGj5t12OsYAidcw=";
  })
  (fetchNuGet {
    pname = "MemoryPack";
    version = "1.21.1";
    hash = "sha256-FMtUCr66kAFj/6oFZyCg16BVh9yTJK+vKLSKo2VZFac=";
  })
  (fetchNuGet {
    pname = "MemoryPack.Core";
    version = "1.21.1";
    hash = "sha256-Frjo5sha/5O3OsLG6ProZ5eAXSxicedjyXfPCx2dM0E=";
  })
  (fetchNuGet {
    pname = "MemoryPack.Generator";
    version = "1.21.1";
    hash = "sha256-o86imC1OyV5teN+sKujffkPDvcITk1l763jFNYyILDY=";
  })
  (fetchNuGet {
    pname = "MemoryPack.Streaming";
    version = "1.21.1";
    hash = "sha256-eOttUpzWeMD0s+49p0sxFc1h+FM7wkU/n2Q4e0S8d2s=";
  })
  (fetchNuGet {
    pname = "MicroCom.Runtime";
    version = "0.11.0";
    hash = "sha256-VdwpP5fsclvNqJuppaOvwEwv2ofnAI5ZSz2V+UEdLF0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNet.WebApi.Client";
    version = "5.2.9";
    hash = "sha256-CCytWp0v8C6NZa+o4cRXvA2u/ZOEA3TiG9+luszAwes=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.WebUtilities";
    version = "8.0.5";
    hash = "sha256-jftUrR5JIodXUs7RR7lzCgzjgxu9D/QGsXfYjS6BbcE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    hash = "sha256-49+H/iFwp+AfCICvWcqo9us4CzxApPKC37Q5Eqrw+JU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "7.0.0";
    hash = "sha256-1e031E26iraIqun84ad0fCIR4MJZ1hcQo4yFN+B7UfE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Build.Tasks.Git";
    version = "8.0.0";
    hash = "sha256-vX6/kPij8vNAu8f7rrvHHhPrNph20IcufmrBgZNxpQA=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.3.4";
    hash = "sha256-qDzTfZBSCvAUu9gzq2k+LOvh6/eRvJ9++VCNck/ZpnE=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.7.0";
    hash = "sha256-nDDpCy8WQADxo7LzWkDupuxs0GCjvuhX8EeKpjTnRP4=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "4.8.0";
    hash = "sha256-3IEinVTZq6/aajMVA8XTRO3LTIEt0PuhGyITGJLtqz4=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.7.0";
    hash = "sha256-0FoP+zHqbhLhyjTPx8I7MCfHqCbmhwE8aRCVe4eC49M=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "4.8.0";
    hash = "sha256-MmOnXJvd/ezs5UPcqyGLnbZz5m+VedpRfB+kFZeeqkU=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Workspaces";
    version = "4.8.0";
    hash = "sha256-WNzc+6mKqzPviOI0WMdhKyrWs8u32bfGj2XwmfL7bwE=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Workspaces.Common";
    version = "4.8.0";
    hash = "sha256-X8R4SpWVO/gpip5erVZf5jCCx8EX3VzIRtNrQiLDIoM=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    hash = "sha256-Enknv2RsFF68lEPdrf5M+BpV1kHoLTVRApKUwuk/pj0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration";
    version = "8.0.0";
    hash = "sha256-9BPsASlxrV8ilmMCjdb3TiUcm5vFZxkBnAI/fNBSEyA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Abstractions";
    version = "8.0.0";
    hash = "sha256-4eBpDkf7MJozTZnOwQvwcfgRKQGcNXe0K/kF+h5Rl8o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.0";
    hash = "sha256-GanfInGzzoN2bKeNwON8/Hnamr6l7RTpYLA49CNXD9Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Binder";
    version = "8.0.1";
    hash = "sha256-KYPQYYspiBGiez7JshmEjy4kFt7ASzVxQeVsygIEvHA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.CommandLine";
    version = "8.0.0";
    hash = "sha256-fmPC/o8S+weTtQJWykpnGHm6AKVU21xYE/CaHYU7zgg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.EnvironmentVariables";
    version = "8.0.0";
    hash = "sha256-+bjFZvqCsMf2FRM2olqx/fub+QwfM1kBhjGVOT5HC48=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.FileExtensions";
    version = "8.0.0";
    hash = "sha256-BCxcjVP+kvrDDB0nzsFCJfU74UK4VBvct2JA4r+jNcs=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.Json";
    version = "8.0.0";
    hash = "sha256-Fi/ijcG5l0BOu7i96xHu96aN5/g7zO6SWQbTsI3Qetg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Configuration.UserSecrets";
    version = "8.0.0";
    hash = "sha256-/yj5QaEzeRStvOFoBpPRPXlEehGtr2E6/rJb+OEPIK8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection";
    version = "8.0.0";
    hash = "sha256-+qIDR8hRzreCHNEDtUcPfVHQdurzWPo/mqviCH78+EQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.0";
    hash = "sha256-75KzEGWjbRELczJpCiJub+ltNUMMbz5A/1KQU+5dgP8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyInjection.Abstractions";
    version = "8.0.1";
    hash = "sha256-lzTYLpRDAi3wW9uRrkTNJtMmaYdtGJJHdBLbUKu60PM=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics";
    version = "8.0.0";
    hash = "sha256-fBLlb9xAfTgZb1cpBxFs/9eA+BlBvF8Xg0DMkBqdHD4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Diagnostics.Abstractions";
    version = "8.0.0";
    hash = "sha256-USD5uZOaahMqi6u7owNWx/LR4EDrOwqPrAAim7iRpJY=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Abstractions";
    version = "8.0.0";
    hash = "sha256-uQSXmt47X2HGoVniavjLICbPtD2ReQOYQMgy3l0xuMU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileProviders.Physical";
    version = "8.0.0";
    hash = "sha256-29y5ZRQ1ZgzVOxHktYxyiH40kVgm5un2yTGdvuSWnRc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.FileSystemGlobbing";
    version = "8.0.0";
    hash = "sha256-+Oz41JR5jdcJlCJOSpQIL5OMBNi+1Hl2d0JUHfES7sU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting";
    version = "8.0.0";
    hash = "sha256-sKHa+w4/pMeQb5RRFqLtMTUJy5H6hSIGWchbH2pxSrg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Hosting.Abstractions";
    version = "8.0.0";
    hash = "sha256-0JBx+wwt5p1SPfO4m49KxNOXPAzAU0A+8tEc/itvpQE=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging";
    version = "8.0.0";
    hash = "sha256-Meh0Z0X7KyOEG4l0RWBcuHHihcABcvCyfUXgasmQ91o=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "3.0.3";
    hash = "sha256-UFawgCAhbN5HCtJy39XO4sz5N/P/Zyrs0uqrQHc4SPI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.0";
    hash = "sha256-Jmddjeg8U5S+iBTwRlVAVLeIHxc4yrrNgqVMOB7EjM4=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Abstractions";
    version = "8.0.1";
    hash = "sha256-TYce3qvMr92JbAZ62ATBsocaH0joJzw0px0tYGZ9N0U=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Configuration";
    version = "8.0.0";
    hash = "sha256-mzmstNsVjKT0EtQcdAukGRifD30T82BMGYlSu8k4K7U=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Console";
    version = "8.0.0";
    hash = "sha256-bdb9YWWVn//AeySp7se87/tCN2E7e8Gx2GPMw28cd9c=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.Debug";
    version = "8.0.0";
    hash = "sha256-AJunzYBZM2wCg86hnPnMrBuWIIyW/4PnIVoDSU969cA=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventLog";
    version = "8.0.0";
    hash = "sha256-vXBm4yhWGP4uow0CqstuqOkxO8yeZEM15JTTenjPbhc=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Logging.EventSource";
    version = "8.0.0";
    hash = "sha256-kaR7YOlq5s8W9nZDtH/lKtnfGbrgOuQY4DUPcA2lcj0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.ObjectPool";
    version = "8.0.6";
    hash = "sha256-GnQgqdQTsoLj09avT9k7ypbbTHKoD61J2Pma4Jm/Pq8=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options";
    version = "8.0.0";
    hash = "sha256-n2m4JSegQKUTlOsKLZUUHHKMq926eJ0w9N9G+I3FoFw=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Options.ConfigurationExtensions";
    version = "8.0.0";
    hash = "sha256-A5Bbzw1kiNkgirk5x8kyxwg9lLTcSngojeD+ocpG1RI=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "8.0.0";
    hash = "sha256-FU8qj3DR8bDdc1c+WeGZx/PCZeqqndweZM9epcpXjSo=";
  })
  (fetchNuGet {
    pname = "Microsoft.Net.Http.Headers";
    version = "8.0.5";
    hash = "sha256-+8nqfm0hq++VkN7EDNEyEpOHCfP9+KqPOkvtY4XPfpA=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    hash = "sha256-LIcg1StDcQLPOABp4JRXIs837d7z0ia6+++3SF3jl1c=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.Common";
    version = "8.0.0";
    hash = "sha256-AfUqleVEqWuHE7z2hNiwOLnquBJ3tuYtbkdGMppHOXc=";
  })
  (fetchNuGet {
    pname = "Microsoft.SourceLink.GitHub";
    version = "8.0.0";
    hash = "sha256-hNTkpKdCLY5kIuOmznD1mY+pRdJ0PKu2HypyXog9vb0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-mBNDmPXNTW54XLnPAUwBRvkIORFM7/j0D0I2SyQPDEg=";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    hash = "sha256-9kylPGfKZc58yFqNKa77stomcoNnMeERXozWJzDcUIA=";
  })
  (fetchNuGet {
    pname = "NetEscapades.EnumGenerators";
    version = "1.0.0-beta07";
    hash = "sha256-SYIuk1B2birutYx6d0vbCshEd8ZEH0pDVrNm9daBxwY=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "1.6.1";
    hash = "sha256-iNan1ix7RtncGWC9AjAZ2sk70DoxOsmEOgQ10fXm4Pw=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.3";
    hash = "sha256-Prh2RPebz/s8AzHb2sPHg3Jl8s31inv9k+Qxd293ybo=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json.Bson";
    version = "1.0.1";
    hash = "sha256-qofIFqViDsdBOE/X0IvzfGUklSrULaH8MoZQ+YrcMOQ=";
  })
  (fetchNuGet {
    pname = "NexusMods.Archives.Nx";
    version = "0.4.0";
    hash = "sha256-U0OXRaGXyBxKNXtntirsCEcGFR7l8LkOLMikHYKP2Wo=";
  })
  (fetchNuGet {
    pname = "NexusMods.Hashing.xxHash64";
    version = "2.0.1";
    hash = "sha256-LSSle8oclFougCUt3dS4syTa856WOWfSZmlBcl7QYhc=";
  })
  (fetchNuGet {
    pname = "NexusMods.MnemonicDB";
    version = "0.9.60";
    hash = "sha256-ZAYK9GDP5RbQopnMwkRE6sX9ULC+mpmAwr0hlonR2wY=";
  })
  (fetchNuGet {
    pname = "NexusMods.MnemonicDB.Abstractions";
    version = "0.9.60";
    hash = "sha256-KErnQeXtPO69zpW+w2MKbBE+r0FbK6+PwH2QXRA4oVA=";
  })
  (fetchNuGet {
    pname = "NexusMods.MnemonicDB.SourceGenerator";
    version = "0.9.60";
    hash = "sha256-KHjTz3q+6gzfBYkwDltcJpCmhAgerE4NcPgSI/Zjr/4=";
  })
  (fetchNuGet {
    pname = "NexusMods.MnemonicDB.Storage";
    version = "0.9.60";
    hash = "sha256-u5ikeysWNCeD1byQD7OzKDeYFaLGCwfj/Qwd18/B3JQ=";
  })
  (fetchNuGet {
    pname = "NexusMods.Paths";
    version = "0.9.4";
    hash = "sha256-W8dIcHvJjhTX2AqjrPBCDpGhDBrJLZ9IewSVo7ffwog=";
  })
  (fetchNuGet {
    pname = "NexusMods.Paths";
    version = "0.9.5";
    hash = "sha256-30IlPuu35i0VrUJSaLy86wSYwVCIDgdZc2HctnKuo6o=";
  })
  (fetchNuGet {
    pname = "NLog";
    version = "5.3.2";
    hash = "sha256-b/y/IFUSe7qsSeJ8JVB0VFmJlkviFb8h934ktnn9Fgc=";
  })
  (fetchNuGet {
    pname = "NLog.Extensions.Logging";
    version = "5.3.11";
    hash = "sha256-DP3R51h+9kk06N63U+1C4/JCZTFiADeYTROToAA2R0g=";
  })
  (fetchNuGet {
    pname = "OneOf";
    version = "3.0.271";
    hash = "sha256-tFWy8Jg/XVJfVOddjXeCAizq/AUljJrq6J8PF6ArYSU=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry";
    version = "1.8.1";
    hash = "sha256-AldbsateY7uhKy/0JM2sEgiOF1wGr5CwTifsuH6Tnuo=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Api";
    version = "1.8.1";
    hash = "sha256-xdMOKY90bGTcvRdBsBqj08Du3qRmDC1BecX+aK3dTTA=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Api.ProviderBuilderExtensions";
    version = "1.8.1";
    hash = "sha256-j4XUh9cnF5SbyhRoNwjOWS3EXIl9ZSEFgkJZjQEN2lM=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Exporter.OpenTelemetryProtocol";
    version = "1.8.1";
    hash = "sha256-smQQOI5i7lG0nnv5CHvzIjCQkago1z+E4W/rnn19iCA=";
  })
  (fetchNuGet {
    pname = "OpenTelemetry.Extensions.Hosting";
    version = "1.8.1";
    hash = "sha256-uA8Lfof/cvQknxBoSDBxTdljAA+oMCOSiUVIsbBOcQc=";
  })
  (fetchNuGet {
    pname = "Pathoschild.Http.FluentClient";
    version = "4.3.0";
    hash = "sha256-F8895rKyjJ0XGo21IjR+qp5BpLaYn9LxMMQ3TRDY7JQ=";
  })
  (fetchNuGet {
    pname = "Projektanker.Icons.Avalonia";
    version = "9.3.0";
    hash = "sha256-rg5XoaMV88f66i4wl7Pe0AMWrPHUwu9QJfPVYnFOgsI=";
  })
  (fetchNuGet {
    pname = "Projektanker.Icons.Avalonia.MaterialDesign";
    version = "9.3.0";
    hash = "sha256-VZR5fR28aLGFKiThbZriPQxbwRFk2Pfrggff8aCO/bs=";
  })
  (fetchNuGet {
    pname = "ReactiveUI";
    version = "18.3.1";
    hash = "sha256-1rf4icGRKTR3XIWJpkQJCG7ObRM+72ITB5K+ND1is9M=";
  })
  (fetchNuGet {
    pname = "ReactiveUI";
    version = "19.5.41";
    hash = "sha256-FsdD1lBZyegqOVzJhZHAz1owCLh7GbVUYXiORbo5euk=";
  })
  (fetchNuGet {
    pname = "ReactiveUI.Fody";
    version = "19.5.41";
    hash = "sha256-LfKELxAfApQLL0fDd7UJCsZML5C4MFN+Gc5ECaBXmUM=";
  })
  (fetchNuGet {
    pname = "Reloaded.Memory";
    version = "9.4.1";
    hash = "sha256-bXaTAUx+/SiiMLmxuPumV9z5w1HcHpzEoNuR+xNhafs=";
  })
  (fetchNuGet {
    pname = "RocksDB";
    version = "8.11.3.46984";
    hash = "sha256-kCSgenerSMTh5h/hHoueV45uuAARRsJi94c62L2mVEQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-8yLKFt2wQxkEf7fNfzB+cPUCjYn2qbqNgQ1+EeY2h/I=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-dsmTLGvt8HqRkDWP8iKVXJCS+akAzENGXKPV18W2RgI=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-AYh39tgXJVFu8aLi9Y/4rK8yWMaza4S4eaxjfcuEEL4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-6MYj0RmLh4EVqMtO/MRqBi0HOn5iG4x9JimgCCJ+EFM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-BgHxXCIbicVZtpgMimSXixhFC3V+p5ODqeljDjO8hCs=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-DWnXs4vlKoU6WxxvCArTJupV6sX3iBbZh8SbqfHace8=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Net.Http";
    version = "4.3.0";
    hash = "sha256-c556PyheRwpYhweBjSfIwEyZHnAUB8jWioyKEcp/2dg=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-2IhBv0i6pTcOyr8FFIyfPEaaCHUmJZ8DYwLUwJ+5waw=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.Apple";
    version = "4.3.0";
    hash = "sha256-serkd4A7F6eciPiPJtUyJyxzdAtupEcWIZQ9nptEzIM=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.unix.Microsoft.Win32.Primitives";
    version = "4.3.0";
    hash = "sha256-LZb23lRXzr26tRS5aA0xyB08JxiblPDoA7HBvn6awXg=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Console";
    version = "4.3.0";
    hash = "sha256-AHkdKShTRHttqfMjmi+lPpTuCrM5vd/WRy6Kbtie190=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-Pf4mRl6YDK2x2KMh0WdyNgv0VUNdSKVDLlHqozecy5I=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-pHJ+I6i16MV6m77uhTC6GPY6jWGReE3SSP3fVB59ti0=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-IvgOeA2JuBjKl5yAVGjPYMPDzs9phb3KANs95H9v1w4=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "SHA3.Net";
    version = "2.0.0";
    hash = "sha256-rNwk9ry52bN95FeNqNC29FokNRRzKw3XnojO/UzHlYc=";
  })
  (fetchNuGet {
    pname = "SharpZstd.Interop";
    version = "1.5.5-beta1";
    hash = "sha256-7znMkZV+AXb5FeVNFBCJC7TJ9pmyfF1mmgbRdwFovMk=";
  })
  (fetchNuGet {
    pname = "ShimSkiaSharp";
    version = "2.0.0-rc1";
    hash = "sha256-rzSatpDash9fSNZTo1pp6ghQyGPsoOmi2pwhj1vOuN8=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.3";
    hash = "sha256-WyMAjnQt8ZsuWpGLI89l/f4bHvv+cg7FdTAL7CtJBvs=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.6";
    hash = "sha256-y0wzgwdQXtgl5boCz/EgLWbK3SwC0cFVRUbBxOUPQXc=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.8";
    hash = "sha256-rD5gc4SnlRTXwz367uHm8XG5eAIQpZloGqLRGnvNu0A=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.HarfBuzz";
    version = "2.88.6";
    hash = "sha256-gpHiTuHfiXgbkBkzipXb8EXIatefsod75nyrFdPcwcA=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.HarfBuzz";
    version = "2.88.8";
    hash = "sha256-W9jNuEo/8q+k2aHNC19FfKcBUIEWx2zDcGwM+jDZ1o8=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.3";
    hash = "sha256-eExWAAURgnwwm2fRwsK/rf+TeOAPs2n02XZzC0zeUjU=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.8";
    hash = "sha256-fOmNbbjuTazIasOvPkd2NPmuQHVCWPnow7AxllRGl7Y=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.3";
    hash = "sha256-8G4swiLMr6XS3kjfO/YC1PyoVdfSq7nxZthZZ+KTKqQ=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.6";
    hash = "sha256-7hOMjlYTOiNPLNwfLFUjTcdgiGEtmYUI1EubiRiC6bo=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.8";
    hash = "sha256-CdcrzQHwCcmOCPtS8EGtwsKsgdljnH41sFytW7N9PmI=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.WebAssembly";
    version = "2.88.3";
    hash = "sha256-/SkV2pIZnt0ziSKB7gt7U2Rltk2Id+zOzbmqgfWUtvA=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.WebAssembly";
    version = "2.88.8";
    hash = "sha256-GWWsE98f869LiOlqZuXMc9+yuuIhey2LeftGNk3/z3w=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.3";
    hash = "sha256-2PhMTwRHitT13KCKiZltKIFieAvNY4jBmVZ2ndVynA8=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.6";
    hash = "sha256-ljD4QmAO2/vwA6I8GIUNkONpOzmGsOVJJy9vPDnjVfA=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.8";
    hash = "sha256-b8Vb94rNjwPKSJDQgZ0Xv2dWV7gMVFl5GwTK/QiZPPM=";
  })
  (fetchNuGet {
    pname = "Spectre.Console";
    version = "0.49.1";
    hash = "sha256-tqSVojyuQjuB34lXo759NOcyLgNIw815mKXJPq5JFDo=";
  })
  (fetchNuGet {
    pname = "Splat";
    version = "14.4.1";
    hash = "sha256-i1yzIVpKdFjZMI4J8H970nZCxszklgDitYTEKKz0zA8=";
  })
  (fetchNuGet {
    pname = "Splat";
    version = "14.8.12";
    hash = "sha256-9KTsYPHVN/wiL8/Yy1KQafrFRy7x8VCEHdzgB+9+8SU=";
  })
  (fetchNuGet {
    pname = "Splat";
    version = "15.0.1";
    hash = "sha256-IDI88gPTOHrBBp4fIwT85K7CkK1AK1FJwgQkCHrgZg0=";
  })
  (fetchNuGet {
    pname = "Splat.Microsoft.Extensions.Logging";
    version = "15.0.1";
    hash = "sha256-Nk+ktdAIuXfSOj2dBcC0TbCe4ghEW1yOOhp5gcBOpb8=";
  })
  (fetchNuGet {
    pname = "Svg.Custom";
    version = "2.0.0-rc1";
    hash = "sha256-9GbCNRjVodohzjqJkuHZV1sNuwO8rA2nYSSdd48YAHk=";
  })
  (fetchNuGet {
    pname = "Svg.Model";
    version = "2.0.0-rc1";
    hash = "sha256-msdN/k77sF2EitKy5hufHZ5DK/fjKWXV+CM8U9T543k=";
  })
  (fetchNuGet {
    pname = "Svg.Skia";
    version = "2.0.0-rc1";
    hash = "sha256-iKQOenzOfAGwmt8Tteb19L/WjY0c6aVQWJfW2DFAF9g=";
  })
  (fetchNuGet {
    pname = "System.AppContext";
    version = "4.3.0";
    hash = "sha256-yg95LNQOwFlA1tWxXdQkVyJqT4AnoDc+ACmrNvzGiZg=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.3.0";
    hash = "sha256-XqZWb4Kd04960h4U9seivjKseGA/YEIpdplfHYHQ9jk=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI=";
  })
  (fetchNuGet {
    pname = "System.CodeDom";
    version = "8.0.0";
    hash = "sha256-uwVhi3xcvX7eiOGQi7dRETk3Qx1EfHsUfchZsEto338=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Concurrent";
    version = "4.3.0";
    hash = "sha256-KMY5DfJnDeIsa13DpqvyN8NkReZEMAFnlmNglVoFIXI=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "7.0.0";
    hash = "sha256-9an2wbxue2qrtugYES9awshQg+KfJqajhnhs45kQIdk=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "8.0.0";
    hash = "sha256-F7OVjKNwpqbUh8lTidbqJWYi476nsq9n+6k0+QVRo3w=";
  })
  (fetchNuGet {
    pname = "System.CommandLine";
    version = "2.0.0-beta4.22272.1";
    hash = "sha256-zSO+CYnMH8deBHDI9DHhCPj79Ce3GOzHCyH1/TiHxcc=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "4.5.0";
    hash = "sha256-15yE2NoT9vmL9oGCaxHClQR1jLW1j1ef5hHMg55xRso=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "5.0.0";
    hash = "sha256-0pST1UHgpeE6xJrYf5R+U7AwIlH3rVC3SpguilI/MAg=";
  })
  (fetchNuGet {
    pname = "System.Composition";
    version = "7.0.0";
    hash = "sha256-YjhxuzuVdAzRBHNQy9y/1ES+ll3QtLcd2o+o8wIyMao=";
  })
  (fetchNuGet {
    pname = "System.Composition.AttributedModel";
    version = "7.0.0";
    hash = "sha256-3s52Dyk2J66v/B4LLYFBMyXl0I8DFDshjE+sMjW4ubM=";
  })
  (fetchNuGet {
    pname = "System.Composition.Convention";
    version = "7.0.0";
    hash = "sha256-N4MkkBXSQkcFKsEdcSe6zmyFyMmFOHmI2BNo3wWxftk=";
  })
  (fetchNuGet {
    pname = "System.Composition.Hosting";
    version = "7.0.0";
    hash = "sha256-7liQGMaVKNZU1iWTIXvqf0SG8zPobRoLsW7q916XC3M=";
  })
  (fetchNuGet {
    pname = "System.Composition.Runtime";
    version = "7.0.0";
    hash = "sha256-Oo1BxSGLETmdNcYvnkGdgm7JYAnQmv1jY0gL0j++Pd0=";
  })
  (fetchNuGet {
    pname = "System.Composition.TypedParts";
    version = "7.0.0";
    hash = "sha256-6ZzNdk35qQG3ttiAi4OXrihla7LVP+y2fL3bx40/32s=";
  })
  (fetchNuGet {
    pname = "System.Console";
    version = "4.3.0";
    hash = "sha256-Xh3PPBZr0pDbDaK8AEHbdGz7ePK6Yi1ZyRWI1JM6mbo=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "4.3.0";
    hash = "sha256-OFJRb0ygep0Z3yDBLwAgM/Tkfs4JCDtsNhwDH9cd1Xw=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "8.0.0";
    hash = "sha256-+aODaDEQMqla5RYZeq0Lh66j+xkPYxykrVvSCmJQ+Vs=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.EventLog";
    version = "8.0.0";
    hash = "sha256-rt8xc3kddpQY4HEdghlBeOK4gdw5yIj4mcZhAVtk2/Y=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tools";
    version = "4.3.0";
    hash = "sha256-gVOv1SK6Ape0FQhCVlNOd9cvQKBvMxRX9K0JPVi8w0Y=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Tracing";
    version = "4.3.0";
    hash = "sha256-hCETZpHHGVhPYvb4C0fh4zs+8zv4GPoixagkLZjpa9Q=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Calendars";
    version = "4.3.0";
    hash = "sha256-uNOD0EOVFgnS2fMKvMiEtI9aOw00+Pfy/H+qucAQlPc=";
  })
  (fetchNuGet {
    pname = "System.Globalization.Extensions";
    version = "4.3.0";
    hash = "sha256-mmJWA27T0GRVuFP9/sj+4TrR4GJWrzNIk2PDrbr7RQk=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression";
    version = "4.3.0";
    hash = "sha256-f5PrQlQgj5Xj2ZnHxXW8XiOivaBvfqDao9Sb6AVinyA=";
  })
  (fetchNuGet {
    pname = "System.IO.Compression.ZipFile";
    version = "4.3.0";
    hash = "sha256-WQl+JgWs+GaRMeiahTFUbrhlXIHapzcpTFXbRvAtvvs=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem";
    version = "4.3.0";
    hash = "sha256-vNIYnvlayuVj0WfRfYKpDrhDptlhp1pN8CYmlVd2TXw=";
  })
  (fetchNuGet {
    pname = "System.IO.FileSystem.Primitives";
    version = "4.3.0";
    hash = "sha256-LMnfg8Vwavs9cMnq9nNH8IWtAtSfk0/Fy4s4Rt9r1kg=";
  })
  (fetchNuGet {
    pname = "System.IO.Hashing";
    version = "8.0.0";
    hash = "sha256-szOGt0TNBo6dEdC3gf6H+e9YW3Nw0woa6UnCGGGK5cE=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.0";
    hash = "sha256-xfjF4UqTMJpf8KsBWUyJlJkzPTOO/H5MW023yTYNQSA=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.3";
    hash = "sha256-v+FOmjRRKlDtDW6+TfmyMiiki010YGVTa0EwXu9X7ck=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "7.0.0";
    hash = "sha256-W2181khfJUTxLqhuAVRhCa52xZ3+ePGOLIPwEN8WisY=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "8.0.0";
    hash = "sha256-LdpB1s4vQzsOODaxiKstLks57X9DTD5D6cPx8DE1wwE=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Linq.Async";
    version = "6.0.1";
    hash = "sha256-uH5fZhcyQVtnsFc6GTUaRRrAQm05v5euJyWCXSFSOYI=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    hash = "sha256-+3pvhZY7rip8HCbfdULzjlC9FPZFpYoQxhkcuFm2wk8=";
  })
  (fetchNuGet {
    pname = "System.Management";
    version = "8.0.0";
    hash = "sha256-HwpfDb++q7/vxR6q57mGFgl5U0vxy+oRJ6orFKORfP0=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Net.Http";
    version = "4.3.0";
    hash = "sha256-UoBB7WPDp2Bne/fwxKF0nE8grJ6FzTMXdT/jfsphj8Q=";
  })
  (fetchNuGet {
    pname = "System.Net.NameResolution";
    version = "4.3.0";
    hash = "sha256-eGZwCBExWsnirWBHyp2sSSSXp6g7I6v53qNmwPgtJ5c=";
  })
  (fetchNuGet {
    pname = "System.Net.Primitives";
    version = "4.3.0";
    hash = "sha256-MY7Z6vOtFMbEKaLW9nOSZeAjcWpwCtdO7/W1mkGZBzE=";
  })
  (fetchNuGet {
    pname = "System.Net.Sockets";
    version = "4.3.0";
    hash = "sha256-il7dr5VT/QWDg/0cuh+4Es2u8LY//+qqiY9BZmYxSus=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.4.0";
    hash = "sha256-auXQK2flL/JpnB/rEcAcUm4vYMCYMEMiWOCAlIaqu2U=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    hash = "sha256-qdSTIFgf2htPS+YhLGjAGiLN8igCYJnCCo6r78+Q+c8=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    hash = "sha256-gtmRkWP2Kwr3nHtDh0yYtce38z1wrGzb6fjm4v8wN6Q=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "5.0.0";
    hash = "sha256-M5Z8pw8rVb8ilbnTdaOptzk5VFd5DlKa7zzCpuytTtE=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.0";
    hash = "sha256-hXB18OsiUHSCmRF3unAfdUEcbXVbG6/nZxcyz13oe9Y=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.1";
    hash = "sha256-Lo5UMqp8DsbVSUxa2UpClR1GoYzqQQcSxkfyFqB/d4Q=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    hash = "sha256-5LhkDmhy2FkSxulXR+bsTtMzdU3VyyuZzsxp7/DwyIU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.7.0";
    hash = "sha256-Fw/CSRD+wajH1MqfKS3Q/sIrUH7GN4K+F+Dx68UPNIg=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    hash = "sha256-mKRknEHNls4gkRwrEgi39B+vSaAz/Gt3IALtS98xNnA=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    hash = "sha256-rKx4a9yZKcajloSZHr4CKTVJ6Vjh95ni+zszPxWjh2I=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "7.0.0";
    hash = "sha256-GwAKQhkhPBYTqmRdG9c9taqrKSKDwyUgOEhWLKxWNPI=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.3.0";
    hash = "sha256-4U4/XNQAnddgQIHIJq3P2T80hN0oPdU2uCeghsDTWng=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.3";
    hash = "sha256-lnZMUqRO4RYRUeSO8HSJ9yBHqFHLVbmenwHWkIU20ak=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices.RuntimeInformation";
    version = "4.3.0";
    hash = "sha256-MYpl6/ZyC6hjmzWRIe+iDoldOMW1mfbwXsduAnXIKGA=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Numerics";
    version = "4.3.0";
    hash = "sha256-P5jHCgMbgFMYiONvzmaKFeOqcAIDPu/U8bOVrNPYKqc=";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    hash = "sha256-ueSG+Yn82evxyGBnE49N4D+ngODDXgornlBtQ3Omw54=";
  })
  (fetchNuGet {
    pname = "System.Security.Claims";
    version = "4.3.0";
    hash = "sha256-Fua/rDwAqq4UByRVomAxMPmDBGd5eImRqHVQIeSxbks=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Algorithms";
    version = "4.3.0";
    hash = "sha256-tAJvNSlczYBJ3Ed24Ae27a55tq/n4D3fubNQdwcKWA8=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Cng";
    version = "4.3.0";
    hash = "sha256-u17vy6wNhqok91SrVLno2M1EzLHZm6VMca85xbVChsw=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Csp";
    version = "4.3.0";
    hash = "sha256-oefdTU/Z2PWU9nlat8uiRDGq/PGZoSPRgkML11pmvPQ=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Encoding";
    version = "4.3.0";
    hash = "sha256-Yuge89N6M+NcblcvXMeyHZ6kZDfwBv3LPMDiF8HhJss=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-DL+D2sc2JrQiB4oAcUggTFyD8w3aLEjJfod5JPe+Oz4=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.Primitives";
    version = "4.3.0";
    hash = "sha256-fnFi7B3SnVj5a+BbgXnbjnGNvWrCEU6Hp/wjsjWz318=";
  })
  (fetchNuGet {
    pname = "System.Security.Cryptography.X509Certificates";
    version = "4.3.0";
    hash = "sha256-MG3V/owDh273GCUPsGGraNwaVpcydupl3EtPXj6TVG0=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal";
    version = "4.3.0";
    hash = "sha256-rjudVUHdo8pNJg2EVEn0XxxwNo5h2EaYo+QboPkXlYk=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "4.3.0";
    hash = "sha256-mbdLVUcEwe78p3ZnB6jYsizNEqxMaCAWI3tEQNhRQAE=";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    hash = "sha256-CBOQwl9veFkrKK2oU8JFFEiKIh/p+aJO+q9Tc2Q/89Y=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "7.0.0";
    hash = "sha256-eCKTVwumD051ZEcoJcDVRGnIGAsEvKpfH3ydKluHxmo=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.Extensions";
    version = "4.3.0";
    hash = "sha256-vufHXg8QAKxHlujPHHcrtGwAqFmsCD6HKjfDAiHyAYc=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "7.0.0";
    hash = "sha256-tF8qt9GZh/nPy0mEnj6nKLG4Lldpoi/D8xM5lv2CoYQ=";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "8.0.0";
    hash = "sha256-IUQkQkV9po1LC0QsqrilqwNzPvnc+4eVvq+hCvq8fvE=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "7.0.0";
    hash = "sha256-198zqA6NR4lGCKgpdy/ptkS0jsYRT6KUjewtfi4Fi2k=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.0";
    hash = "sha256-XFcCHMW1u2/WujlWNHaIWkbW1wn8W4kI0QdrwPtWmow=";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "8.0.3";
    hash = "sha256-ljBBGkResXv3MbrA14hR6QXo8SFLLV52GkpA+wxKdEo=";
  })
  (fetchNuGet {
    pname = "System.Text.RegularExpressions";
    version = "4.3.0";
    hash = "sha256-VLCk1D1kcN2wbAe3d0YQM/PqCsPHOuqlBY1yd2Yo+K0=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "7.0.0";
    hash = "sha256-Cu0gjQsLIR8Yvh0B4cOPJSYVq10a+3F9pVz/C43CNeM=";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "8.0.0";
    hash = "sha256-c5TYoLNXDLroLIPnlfyMHk7nZ70QAckc/c7V199YChg=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.3.0";
    hash = "sha256-X2hQ5j+fxcmnm88Le/kSavjiGOmkcumBGTZKBLvorPc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "System.Threading.ThreadPool";
    version = "4.3.0";
    hash = "sha256-wW0QdvssRoaOfQLazTGSnwYTurE4R8FxDx70pYkL+gg=";
  })
  (fetchNuGet {
    pname = "System.Threading.Timer";
    version = "4.3.0";
    hash = "sha256-pmhslmhQhP32TWbBzoITLZ4BoORBqYk25OWbru04p9s=";
  })
  (fetchNuGet {
    pname = "System.Xml.ReaderWriter";
    version = "4.3.0";
    hash = "sha256-QQ8KgU0lu4F5Unh+TbechO//zaAGZ4MfgvW72Cn1hzA=";
  })
  (fetchNuGet {
    pname = "System.Xml.XDocument";
    version = "4.3.0";
    hash = "sha256-rWtdcmcuElNOSzCehflyKwHkDRpiOhJJs8CeQ0l1CCI=";
  })
  (fetchNuGet {
    pname = "TextMateSharp";
    version = "1.0.56";
    hash = "sha256-uf0Kt7Wd2GEEbFxXeaLd7fEpLl6LP1ESLOC2/BjNYNk=";
  })
  (fetchNuGet {
    pname = "TextMateSharp.Grammars";
    version = "1.0.56";
    hash = "sha256-KHX4YmDEJ5RRBtCTOC9YSLEGIKqBiZljPM+3ETqH+8s=";
  })
  (fetchNuGet {
    pname = "Tmds.DBus.Protocol";
    version = "0.16.0";
    hash = "sha256-vKYEaa1EszR7alHj48R8G3uYArhI+zh2ZgiBv955E98=";
  })
  (fetchNuGet {
    pname = "TransparentValueObjects";
    version = "1.0.1";
    hash = "sha256-nTnJNjj0p0ztiZA9DPYdzTWKHXC2C6uQXJG7Pad//rA=";
  })
  (fetchNuGet {
    pname = "ValveKeyValue";
    version = "0.10.0.360";
    hash = "sha256-LPQ6isUsA3cQKiO6ADijrCQ2ucx4TD01+kGzei3jIGY=";
  })
  (fetchNuGet {
    pname = "Vogen";
    version = "3.0.20";
    hash = "sha256-KY7T9ekbqGDUoLYvF6y4iYiMsFFebUoAwpo4FJ6Yg3w=";
  })
  (fetchNuGet {
    pname = "Vogen";
    version = "3.0.24";
    hash = "sha256-erz/30Og8+p6niM/FftOUlGEICfDjNo9MX86ybaKYZQ=";
  })
]
